
def error(msg):
    print(f"error: {msg}")
    exit(1)
